# Generated by Django 3.0.5 on 2024-08-18 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_institution'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
