# Generated by Django 3.0.5 on 2024-08-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_institucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='phone',
            field=models.CharField(default='Sin teléfono', max_length=20),
        ),
    ]
